##
## Makefile for hue in /home/arnaud.alies/rendu/cpp_indie_studio
## 
## Made by arnaud.alies
## Login   <arnaud.alies@epitech.eu>
## 
## Started on  Tue May  2 15:09:04 2017 arnaud.alies
## Last update Tue May  2 17:11:16 2017 arnaud.alies
##

NAME		=	indie_studio

CXX		=	g++

SRC		=	./src/

INC		=	./include/

IRRLICHT_LIB	=	./irrlicht-1.8.4/lib/Linux/
IRRLITCHT_INC	=	./irrlicht-1.8.4/include/

ifeq ($(HOSTTYPE), x86_64)
LIBSELECT=64
endif

CXXFLAGS	+=	-std=c++11 -O3 -ffast-math \
			-I$(IRRLITCHT_INC) \
			-I/usr/X11R6/include \
			-I$(INC) \

LDFLAGS		+=	-L/usr/X11R6/lib$(LIBSELECT) -L$(IRRLICHT) -lIrrlicht -lGL -lXxf86vm -lXext -lX11 -lXcursor

SRCS		=	$(SRC)main.cpp \

OBJS		=	$(SRCS:.cpp=.o)

RM		=	rm -f

all:		$(NAME)

$(NAME):	$(OBJS)
		$(CXX) $(OBJS) -o $(NAME) $(LDFLAGS)

clean:
		$(RM) $(OBJS)

fclean:		clean
		$(RM) $(NAME)

re:		fclean all

.PHONY: all clean fclean re ui
